=== Merp/SubaruDefs/RomRaider/logger/logger.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT address ( #PCDATA ) >
<!ATTLIST address length CDATA #IMPLIED >
<!ATTLIST address bit ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 ) #IMPLIED >

<!ELEMENT ecu ( address+ ) >
<!ATTLIST ecu id CDATA #REQUIRED >

<!ELEMENT ref EMPTY >
<!ATTLIST ref ecuparam CDATA #IMPLIED >
<!ATTLIST ref parameter IDREF #IMPLIED >

<!ELEMENT depends ( ref+ ) >

<!ELEMENT replace EMPTY >
<!ATTLIST replace value CDATA #REQUIRED >
<!ATTLIST replace with CDATA #REQUIRED >

<!ELEMENT conversion ( replace* ) >
<!ATTLIST conversion expr CDATA #REQUIRED >
<!ATTLIST conversion format ( 0 | 0.0 | 0.00 | 0.000 | 0.0000 | 0.00000 | 0.000000) #REQUIRED >
<!ATTLIST conversion storagetype ( int8 | int16 | uint8 | uint16 | int32 | float ) #IMPLIED >
<!ATTLIST conversion units CDATA #REQUIRED >
<!ATTLIST conversion gauge_min CDATA #IMPLIED >
<!ATTLIST conversion gauge_max CDATA #IMPLIED >
<!ATTLIST conversion gauge_step CDATA #IMPLIED >

<!ELEMENT conversions ( conversion+ ) >

<!ELEMENT parameter ( ( address+, conversions?) | (depends, conversions?) ) >
<!ATTLIST parameter target CDATA #REQUIRED >
<!ATTLIST parameter ecubit ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 ) #IMPLIED >
<!ATTLIST parameter ecubyteindex CDATA #IMPLIED >
<!ATTLIST parameter desc CDATA #REQUIRED >
<!ATTLIST parameter name CDATA #REQUIRED >
<!ATTLIST parameter id ID #REQUIRED >

<!ELEMENT parameters ( parameter+ ) >

<!ELEMENT switch EMPTY >
<!ATTLIST switch target CDATA #REQUIRED >
<!ATTLIST switch ecubyteindex CDATA #IMPLIED >
<!ATTLIST switch bit ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 ) #REQUIRED >
<!ATTLIST switch byte CDATA #REQUIRED >
<!ATTLIST switch desc CDATA #REQUIRED >
<!ATTLIST switch name CDATA #REQUIRED >
<!ATTLIST switch id ID #REQUIRED >

<!ELEMENT switches ( switch+ ) >

<!ELEMENT dtcode EMPTY >
<!ATTLIST dtcode bit ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 ) #REQUIRED >
<!ATTLIST dtcode memaddr CDATA #REQUIRED >
<!ATTLIST dtcode tmpaddr CDATA #REQUIRED >
<!ATTLIST dtcode desc CDATA #REQUIRED >
<!ATTLIST dtcode name CDATA #REQUIRED >
<!ATTLIST dtcode id ID #REQUIRED >

<!ELEMENT dtcodes ( dtcode+) >

<!ELEMENT ecuparam ( ecu+, conversions? ) >
<!ATTLIST ecuparam target CDATA #REQUIRED >
<!ATTLIST ecuparam desc CDATA #REQUIRED >
<!ATTLIST ecuparam name CDATA #REQUIRED >
<!ATTLIST ecuparam id ID #REQUIRED >

<!ELEMENT ecuparams ( ecuparam+ ) >

<!ELEMENT protocol ( parameters?, switches?, dtcodes?, ecuparams? ) >
<!ATTLIST protocol id ID #REQUIRED >
<!ATTLIST protocol baud CDATA #REQUIRED >
<!ATTLIST protocol databits CDATA #REQUIRED >
<!ATTLIST protocol stopbits CDATA #REQUIRED >
<!ATTLIST protocol parity CDATA #REQUIRED >
<!ATTLIST protocol connect_timeout CDATA #REQUIRED >
<!ATTLIST protocol send_timeout CDATA #REQUIRED >

<!ELEMENT protocols ( protocol+ ) >

<!ELEMENT logger ( protocols ) >
<!ATTLIST logger version CDATA #IMPLIED >

=== Merp/SubaruDefs/RomRaider/logger/MerpMod/base.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE logger SYSTEM "logger.dtd"[]>
<!--ROMRAIDER STANDARD UNITS LOGGER DEFINITION FILE (VERSION 95) 20121018_180935 [en]
Added ECU ID: 7412587207 to extended parameters

TERMS, CONDITIONS, AND DISCLAIMERS
- - - - - - - - - - - - - - - - - - - - - - - - -
WARNING: These definition files are created as the result of the extremely complex and time consuming process
of reverse-engineering the factory ECU. Because of this complexity, it is necessary to make certain assumptions
and, therefore, it is impossible to always deal in absolutes in regards to representations made by these
definitions. In addition, due to this complexity and the numerous variations among different ECUs, it is also
impossible to guarantee that the definitions will not contain errors or other bugs. What this all means is that
there is the potential for bugs, errors and misrepresentations which can result in damage to your motor, your
ECU as well the possibility of causing your vehicle to behave unexpectedly on the road, increasing the risk of
death or injury. Modifications to your vehicle's ECU may also be in violation of local, state and federal laws.
By using these definition files, either directly or indirectly, you agree to assume 100% of all risk and
RomRaider's creators and contributors shall not be held responsible for any damages or injuries you receive.
This product is for advanced users only. There are no safeguards in place when tuning with RomRaider. As such,
the potential for serious damage and injury still exists, even if the user does not experience any bugs or errors.
As always, use at your own risk.

These definitions are created for FREE without any sort of guarantee. The developers cannot be held liable for
any damage or injury incurred as a result of these definitions. USE AT YOUR OWN RISK! -->
<logger version="95">
  <protocols>
    <protocol id="SSM" baud="4800" databits="8" stopbits="1" parity="0" connect_timeout="2000" send_timeout="55">
      <parameters>
        <parameter id="P1" name="Engine Load (Relative)" desc="P1" ecubyteindex="8" ecubit="7" target="1">
          <address>0x000007</address>
          <conversions>
            <conversion units="%" expr="x*100/255" format="0.00" />
          </conversions>
        </parameter>
        <parameter id="P2" name="Coolant Temperature" desc="P2" ecubyteindex="8" ecubit="6" target="1">
          <address>0x000008</address>
          <conversions>
            <conversion units="F" expr="32+9*(x-40)/5" format="0" gauge_min="0" gauge_max="240" gauge_step="30" />
            <conversion units="C" expr="x-40" format="0" gauge_min="-20" gauge_max="120" gauge_step="20" />
          </conversions>
        </parameter>
        <parameter id="P3" name="A/F Correction #1" desc="P3" ecubyteindex="8" ecubit="5" target="1">
          <address>0x000009</address>
          <conversions>
            <conversion units="%" expr="(x-128)*100/128" format="0.00" gauge_min="-20" gauge_max="20" gauge_step="5" />
          </conversions>
        </parameter>
        <parameter id="P4" name="A/F Learning #1" desc="P4" ecubyteindex="8" ecubit="4" target="1">
          <address>0x00000A</address>
          <conversions>
            <conversion units="%" expr="(x-128)*100/128" format="0.00" gauge_min="-20" gauge_max="20" gauge_step="5" />
          </conversions>
        </parameter>
        <parameter id="P5" name="A/F Correction #2" desc="P5" ecubyteindex="8" ecubit="3" target="1">
          <address>0x00000B</address>
          <conversions>
            <conversion units="%" expr="(x-128)*100/128" format="0.00" gauge_min="-20" gauge_max="20" gauge_step="5" />
          </conversions>
        </parameter>
        <parameter id="P6" name="A/F Learning #2" desc="P6" ecubyteindex="8" ecubit="2" target="1">
          <address>0x00000C</address>
          <conversions>
            <conversion units="%" expr="(x-128)*100/128" format="0.00" gauge_min="-20" gauge_max="20" gauge_step="5" />
          </conversions>
        </parameter>
        <parameter id="P7" name="Manifold Absolute Pressure" desc="P7-Pressure value calculated from the manifold absolute pressure sensor (absolute value)" ecubyteindex="8" ecubit="1" target="1">
          <address>0x00000D</address>
          <conversions>
            <conversion units="psi" expr="x*37/255" format="0.00" gauge_min="-20" gauge_max="40" gauge_step="5" />
            <conversion units="bar" expr="x/100" format="0.000" gauge_min="-1.2" gauge_max="2.8" gauge_step="0.4" />
            <conversion units="kPa" expr="x" format="0" gauge_min="-120" gauge_max="280" gauge_step="40" />
            <conversion units="hPa" expr="x*10" format="0" gauge_min="-1200" gauge_max="2800" gauge_step="400" />
            <conversion units="inHg" expr="x*0.2953" format="0.00" gauge_min="-40" gauge_max="60" gauge_step="10" />
            <conversion units="mmHg" expr="x*7.5" format="0" gauge_min="-1000" gauge_max="2000" gauge_step="300" />
          </conversions>
        </parameter>
        <parameter id="P8" name="Engine Speed" desc="P8" ecubyteindex="8" ecubit="0" target="3">
          <address length="2">0x00000E</address>
          <conversions>
            <conversion units="rpm" expr="x/4" format="0" />
          </conversions>
        </parameter>
        <parameter id="P9" name="Vehicle Speed" desc="P9" ecubyteindex="9" ecubit="7" target="1">
          <address>0x000010</address>
          <conversions>
            <conversion units="mph" expr="x*0.621371192" format="0" />
            <conversion units="km/h" expr="x" format="0" />
          </conversions>
        </parameter>
        <parameter id="P10" name="Ignition Total Timing" desc="P10" ecubyteindex="9" ecubit="6" target="1">
          <address>0x000011</address>
          <conversions>
            <conversion units="degrees" expr="(x-128)/2" format="0.00" gauge_min="20" gauge_max="60" gauge_step="10" />
          </conversions>
        </parameter>
        <parameter id="P11" name="Intake Air Temperature" desc="P11" ecubyteindex="9" ecubit="5" target="1">
          <address>0x000012</address>
          <conversions>
            <conversion units="F" expr="32+9*(x-40)/5" format="0" gauge_min="0" gauge_max="140" gauge_step="20" />
            <conversion units="C" expr="x-40" format="0" gauge_min="-20" gauge_max="60" gauge_step="10" />
          </conversions>
        </parameter>
        <parameter id="P12" name="Mass Airflow" desc="P12" ecubyteindex="9" ecubit="4" target="1">
          <address length="2">0x000013</address>
          <conversions>
            <conversion units="g/s" expr="x/100" format="0.00" gauge_min="0" gauge_max="400" gauge_step="20" />
          </conversions>
        </parameter>
        <parameter id="P13" name="Throttle Opening Angle" desc="P13-Engine throttle opening angle." ecubyteindex="9" ecubit="3" target="1">
          <address>0x000015</address>
          <conversions>
            <conversion units="%" expr="x*100/255" format="0.00" />
          </conversions>
        </parameter>
        <parameter id="P14" name="Front O2 Sensor #1" desc="P14" ecubyteindex="9" ecubit="2" target="1">
          <address length="2">0x000016</address>
          <conversions>
            <conversion units="V" expr="x/200" format="0.00" />
          </conversions>
        </parameter>
        <parameter id="P15" name="Rear O2 Sensor" desc="P15" ecubyteindex="9" ecubit="1" target="1">
          <address length="2">0x000018</address>
          <conversions>
            <conversion units="V" expr="x/200" format="0.00" />
          </conversions>
        </parameter>
        <parameter id="P16" name="Front O2 Sensor #2" desc="P16" ecubyteindex="9" ecubit="0" target="1">
          <address length="2">0x00001A</address>
          <conversions>
            <conversion units="V" expr="x/200" format="0.00" />
          </conversions>
        </parameter>
        <parameter id="P17" name="Battery Voltage" desc="P17" ecubyteindex="10" ecubit="7" target="3">
          <address>0x00001C</address>
          <conversions>
            <conversion units="V" expr="x*8/100" format="0.00" gauge_min="0" gauge_max="20" gauge_step="2" />
          </conversions>
        </parameter>
        <parameter id="P18" name="Mass Airflow Sensor Voltage" desc="P18" ecubyteindex="10" ecubit="6" target="3">
          <address>0x00001D</address>
          <conversions>
            <conversion units="V" expr="x/50" format="0.00" />
          </conversions>
        </parameter>
        <parameter id="P19" name="Throttle Sensor Voltage" desc="P19" ecubyteindex="10" ecubit="5" target="3">
          <address>0x00001E</address>
          <conversions>
            <conversion units="V" expr="x/50" format="0.00" />
          </conversions>
        </parameter>
        <parameter id="P20" name="Differential Pressure Sensor Voltage" desc="P20" ecubyteindex="10" ecubit="4" target="1">
          <address>0x00001F</address>
          <conversions>
            <conversion units="V" expr="x/50" format="0.00" />
          </conversions>
        </parameter>
        <parameter id="P21" name="Fuel Injector #1 Pulse Width" desc="P21-This parameter includes injector latency." ecubyteindex="10" ecubit="3" target="1">
          <address>0x000020</address>
          <conversions>
            <conversion units="ms" expr="x*256/1000" format="0.00" />
            <conversion units="µs" expr="x*256" format="0.00" />
          </conversions>
        </parameter>
        <parameter id="P22" name="Fuel Injector #2 Pulse Width" desc="P22-This parameter includes injector latency." ecubyteindex="10" ecubit="2" target="1">
          <address>0x000021</address>
          <conversions>
            <conversion units="ms" expr="x*256/1000" format="0.00" />
            <conversion units="µs" expr="x*256" format="0.00" />
          </conversions>
        </parameter>
